linters:
  enable:
    - gofmt
    - gocyclo
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `` is not checked
  exclude-rules:
    - path: cmd/gnmi_cli
      linters:
        - staticcheck
        - scopelint
